---
data:
  _extendedDependsOn: []
  _extendedRequiredBy: []
  _extendedVerifiedWith: []
  _pathExtension: cpp
  _verificationStatusIcon: ':x:'
  attributes: {}
  bundledCode: "Traceback (most recent call last):\n  File \"/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/onlinejudge_verify/documentation/build.py\"\
    , line 71, in _render_source_code_stat\n    bundled_code = language.bundle(stat.path,\
    \ basedir=basedir, options={'include_paths': [basedir]}).decode()\n  File \"/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/onlinejudge_verify/languages/cplusplus.py\"\
    , line 193, in bundle\n    bundler.update(path)\n  File \"/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/onlinejudge_verify/languages/cplusplus_bundle.py\"\
    , line 401, in update\n    self.update(self._resolve(pathlib.Path(included), included_from=path))\n\
    \  File \"/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/onlinejudge_verify/languages/cplusplus_bundle.py\"\
    , line 260, in _resolve\n    raise BundleErrorAt(path, -1, \"no such header\"\
    )\nonlinejudge_verify.languages.cplusplus_bundle.BundleErrorAt: ../template.cpp:\
    \ line -1: no such header\n"
  code: "#define PROBLEM \"https://yukicoder.me/problems/1601\"\n\n#include \"../template.cpp\"\
    \n\n#include \"../DataStructure/RangeSet.cpp\"\n\nsigned main(){\n    ll d,q;cin>>d>>q;\n\
    \    RangeSet<ll> st;\n    ll res=0;\n    while(q--){\n        ll l,r;cin>>l>>r;\n\
    \        st.insert(l,r);\n        auto p=st.covered_by(l);\n        chmax(res,p.second-p.first+1);\n\
    \        cout<<res<<\"\\n\";\n    }\n    return 0;\n}"
  dependsOn: []
  isVerificationFile: true
  path: test/yuki1601.test.cpp
  requiredBy: []
  timestamp: '1970-01-01 00:00:00+00:00'
  verificationStatus: TEST_WRONG_ANSWER
  verifiedWith: []
documentation_of: test/yuki1601.test.cpp
layout: document
redirect_from:
- /verify/test/yuki1601.test.cpp
- /verify/test/yuki1601.test.cpp.html
title: test/yuki1601.test.cpp
---
